/* KOPEYKA CLOUD v3 — deterministic auth/load/save */
(function(){'use strict';
const URL='https://cqslrfphsjllhltsvvuq.supabase.co',KEY='sb_publishable_cM_XCycYRFLIc6qEqlH83Q_5XY6kPzG';
let sb=null,ready=false,saving=false,lastSent='';
function loadSDK(){return new Promise((ok,bad)=>{if(window.supabase)return ok();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
function client(){if(!sb&&window.supabase)sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
function indicator(t){let x=document.getElementById('kc-cloud');if(!x){x=document.createElement('div');x.id='kc-cloud';x.style.cssText='position:fixed;top:10px;left:50%;transform:translateX(-50%);z-index:30000;font:11px sans-serif;color:var(--safe);background:var(--surface);padding:5px 9px;border-radius:9px';document.body.appendChild(x)}x.textContent=t}
function auth(){if(document.getElementById('kc-auth'))return;const x=document.createElement('div');x.id='kc-auth';x.style.cssText='position:fixed;inset:0;z-index:29999;background:rgba(0,0,0,.7);display:flex;align-items:center;justify-content:center;padding:18px';x.innerHTML='<div style="width:min(430px,100%);background:var(--surface);border:1px solid var(--border);border-radius:22px;padding:24px"><h2>Копейка</h2><p>Войди в аккаунт, чтобы данные были доступны на всех устройствах.</p><input id="kc-email" type="email" placeholder="Email" style="width:100%;margin:8px 0;padding:13px"><input id="kc-pass" type="password" placeholder="Пароль" style="width:100%;margin:8px 0;padding:13px"><div style="display:flex;gap:8px;margin-top:12px"><button class="btn btn-secondary" id="kc-signup">Создать аккаунт</button><button class="btn btn-primary" id="kc-login">Войти</button></div><div id="kc-msg" style="font-size:12px;margin-top:10px"></div></div>';document.body.appendChild(x);document.getElementById('kc-login').onclick=()=>doAuth(false);document.getElementById('kc-signup').onclick=()=>doAuth(true)}
function authMsg(t){auth();document.getElementById('kc-msg').textContent=t}
async function doAuth(signup){const email=document.getElementById('kc-email').value.trim(),password=document.getElementById('kc-pass').value;if(!email||password.length<6)return authMsg('Введите email и пароль минимум из 6 символов.');const c=client();authMsg(signup?'Создаю аккаунт…':'Выполняю вход…');try{const r=signup?await c.auth.signUp({email,password}):await c.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(signup&&!r.data.session)return authMsg('Подтверди email, затем войди.');await syncSession(r.data.session)}catch(e){authMsg(e.message||'Ошибка авторизации')}}
function closeAuth(){const x=document.getElementById('kc-auth');if(x)x.remove()}
async function syncSession(session){if(!session?.user){ready=false;auth();return}const c=client();closeAuth();indicator('загрузка облака…');const q=await c.from('user_finance_state').select('state,version,updated_at').eq('user_id',session.user.id).maybeSingle();if(q.error){console.error('CLOUD LOAD',q.error);indicator('ошибка чтения облака');return}if(q.data&&q.data.state){window.STATE=q.data.state;lastSent=JSON.stringify(window.STATE);localStorage.setItem('__state_v3__',lastSent);ready=true;if(typeof window.render==='function')window.render();indicator('облако подключено');return}ready=true;await saveCloud(true);indicator('облако подключено')}
async function saveCloud(force){if(!ready||saving)return;const c=client();if(!c||!window.STATE)return;saving=true;try{const ruser=await c.auth.getUser();if(ruser.error||!ruser.data.user)throw ruser.error||new Error('Нет пользователя');const json=JSON.stringify(window.STATE);if(!force&&json===lastSent)return;const r=await c.from('user_finance_state').upsert({user_id:ruser.data.user.id,state:window.STATE,version:3,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error)throw r.error;lastSent=json;localStorage.setItem('__state_v3__',json);indicator('облако сохранено')}catch(e){console.error('CLOUD SAVE',e);indicator('ошибка сохранения')}finally{saving=false}}
function hook(){['saveState','persist'].forEach(name=>{const old=window[name];if(typeof old!=='function'||old.__cloud3)return;window[name]=function(){const r=old.apply(this,arguments);if(ready)setTimeout(()=>saveCloud(true),0);return r};window[name].__cloud3=true})}
async function boot(){try{await loadSDK();const c=client();auth();hook();const session=await c.auth.getSession();if(session.error)throw session.error;if(session.data.session)await syncSession(session.data.session);else auth();c.auth.onAuthStateChange((_e,s)=>setTimeout(()=>syncSession(s),50));setInterval(()=>{hook();if(ready)saveCloud(false)},1000)}catch(e){console.error('CLOUD BOOT',e);authMsg('Ошибка подключения к облаку')}}
window.kopeykaCloud={save:()=>saveCloud(true),logout:async()=>{await client().auth.signOut();ready=false;auth()}};boot();
})();