/* KOPEYKA AUTH CLOUD v1 — Supabase Auth + per-user finance state */
(function(){'use strict';
const URL='https://cqslrfphsjllhltsvvuq.supabase.co';
const KEY='sb_publishable_cM_XCycYRFLIc6qEqlH83Q_5XY6kPzG';
let sb=null,syncing=false,ready=false,lastSent='';
const $=s=>document.querySelector(s);
function ensureClient(){if(sb)return sb;if(!window.supabase)return null;sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
function authUI(){if($('#kc-auth'))return;const st=document.createElement('style');st.textContent='.kc-auth{position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.7);display:flex;align-items:center;justify-content:center;padding:18px}.kc-box{width:min(430px,100%);background:var(--surface);border:1px solid var(--border);border-radius:22px;padding:24px;box-shadow:var(--shadow)}.kc-box h2{margin:0 0 7px}.kc-box p{color:var(--text-dim);font-size:13px;line-height:1.45}.kc-field{margin:12px 0}.kc-field label{display:block;font-size:12px;color:var(--text-dim);margin-bottom:6px}.kc-field input{width:100%;padding:13px;border-radius:12px;border:1px solid var(--border);background:var(--surface-2);color:var(--text);font-size:15px}.kc-actions{display:flex;gap:8px;margin-top:16px}.kc-actions button{flex:1}.kc-msg{font-size:12px;margin-top:10px;min-height:18px}.kc-user{position:fixed;top:10px;right:58px;z-index:21;font-size:10px;color:var(--text-dim);max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.kc-cloud{position:fixed;top:12px;left:50%;transform:translateX(-50%);z-index:21;font-size:10px;color:var(--safe);opacity:.85}';document.head.appendChild(st)}
function showAuth(msg){authUI();let x=$('#kc-auth');if(!x){x=document.createElement('div');x.id='kc-auth';x.className='kc-auth';x.innerHTML='<div class="kc-box"><h2>Копейка</h2><p>Войди в аккаунт, чтобы данные сохранялись в облаке и были доступны с телефона, другого браузера и компьютера.</p><div class="kc-field"><label>Email</label><input id="kc-email" type="email" autocomplete="email"></div><div class="kc-field"><label>Пароль</label><input id="kc-pass" type="password" autocomplete="current-password"></div><div class="kc-actions"><button class="btn btn-secondary" id="kc-signup">Создать аккаунт</button><button class="btn btn-primary" id="kc-login">Войти</button></div><div class="kc-msg" id="kc-msg"></div></div>';document.body.appendChild(x);$('#kc-login').onclick=()=>login(false);$('#kc-signup').onclick=()=>login(true)}if(msg)$('#kc-msg').textContent=msg;x.style.display='flex'}
function hideAuth(){const x=$('#kc-auth');if(x)x.style.display='none'}
async function login(signup){const email=$('#kc-email')?.value.trim(),pass=$('#kc-pass')?.value;if(!email||pass.length<6){$('#kc-msg').textContent='Введите email и пароль минимум из 6 символов.';return}const c=ensureClient();$('#kc-msg').textContent=signup?'Создаю аккаунт…':'Выполняю вход…';try{const r=signup?await c.auth.signUp({email,password:pass}):await c.auth.signInWithPassword({email,password:pass});if(r.error)throw r.error;if(signup&&!r.data.session){$('#kc-msg').textContent='Аккаунт создан. Подтверди email, затем войди.';return}await onSession(r.data.session)}catch(e){$('#kc-msg').textContent=e.message||'Ошибка авторизации'}}
async function onSession(session){if(!session?.user){ready=false;showAuth();return}hideAuth();const u=$('#kc-user')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'kc-user',className:'kc-user'}));u.textContent=session.user.email||session.user.id;const c=ensureClient();const {data,error}=await c.from('user_finance_state').select('state,version,updated_at').eq('user_id',session.user.id).maybeSingle();if(error){console.error(error);cloudIndicator('ошибка чтения облака');return}if(data?.state){STATE=data.state;if(typeof saveState==='function')saveState();lastSent=JSON.stringify(STATE);if(typeof render==='function')render()}else{ready=true;await saveCloud(true)}ready=true;cloudIndicator('облако подключено')}
async function saveCloud(force){if(!ready&&!force)return;const c=ensureClient();if(!c||!window.STATE||syncing)return;syncing=true;try{const {data:{user}}=await c.auth.getUser();if(!user)return;const json=JSON.stringify(STATE);if(!force&&json===lastSent)return;const {error}=await c.from('user_finance_state').upsert({user_id:user.id,state:STATE,version:1,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;lastSent=json;cloudIndicator('облако сохранено')}catch(e){console.error('Kopeyka cloud',e);cloudIndicator('ошибка облака')}finally{syncing=false}}
function cloudIndicator(t){authUI();let x=$('#kc-cloud');if(!x){x=document.createElement('div');x.id='kc-cloud';x.className='kc-cloud';document.body.appendChild(x)}x.textContent=t}
function hook(){['saveState','persist'].forEach(name=>{const fn=window[name];if(typeof fn!=='function'||fn.__kc)return;window[name]=function(){const r=fn.apply(this,arguments);if(ready)setTimeout(()=>saveCloud(true),50);return r};window[name].__kc=true})}
async function boot(){if(!ensureClient()){setTimeout(boot,100);return}authUI();hook();const {data:{session}}=await sb.auth.getSession();if(session)await onSession(session);else showAuth();sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>onSession(s),0));setInterval(()=>{hook();if(ready)saveCloud(false)},1500)}
window.kopeykaCloud={save:()=>saveCloud(true),logout:async()=>{await ensureClient().auth.signOut();ready=false;showAuth()}};boot();
})();