/* Копейка — v4 post-fix enhancements */
(() => {
  'use strict';
  if (window.__KOPEYKA_ENHANCEMENTS_V4__) return;
  window.__KOPEYKA_ENHANCEMENTS_V4__ = true;

  const RATE=4800, MODE_KEY='kopeyka:daily-mode:v1', PLANS_KEY='kopeyka:plans:v1', OBL_KEY='kopeyka:obligations:v1', REPORTS_KEY='kopeyka:monthly-reports:v1';
  const fmt=n=>Math.round(Number(n)||0).toLocaleString('ru-RU')+' ₽';
  const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;};
  const today=()=>{const n=new Date();return new Date(n.getFullYear(),n.getMonth(),n.getDate());};
  const dateOnly=v=>{const [y,m,d]=String(v).slice(0,10).split('-').map(Number);return new Date(y,m-1,d);};
  const future=v=>dateOnly(v)>today();
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'');}catch{return f;}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
  const txs=()=>Array.isArray(window.txs)?window.txs:[];
  const isIncome=t=>t.type==='Доход'&&t.category!=='Накопление';
  const isSaving=t=>t.type==='Накопление'||(t.type==='Доход'&&t.category==='Накопление');
  const isExpense=t=>t.type==='Расход';
  const DEFAULT_OBL=[{id:'alimony',name:'Алименты',amount:25000},{id:'food',name:'Коммуналка + продукты',amount:8000},{id:'connect',name:'Связь + VPN',amount:700},{id:'claude',name:'Подписка Claude',amount:2000}];
  const obligations=()=>read(OBL_KEY,DEFAULT_OBL);
  const cycle=['Выходной','Выходной','День','День','Ночь','Ночь'],anchor=new Date(2026,8,1);
  const work=d=>{const n=Math.round((dateOnly(d)-anchor)/86400000),i=((n%6)+6)%6;return cycle[i]!=='Выходной';};
  const shifts=(y,m,a,b)=>{let n=0,last=new Date(y,m+1,0).getDate();for(let d=a;d<=Math.min(b,last);d++)if(work(new Date(y,m,d)))n++;return n;};
  const halfSalary=(y,m,h)=>shifts(y,m,h===1?1:16,h===1?15:new Date(y,m+1,0).getDate())*RATE;
  const nextSalary=()=>{const n=today(),out=[];for(let k=-2;k<=4;k++){const m=n.getMonth()+k,y=n.getFullYear();out.push({date:new Date(y,m,25),amount:halfSalary(y,m,1)});out.push({date:new Date(y,m+1,10),amount:halfSalary(y,m,2)});}return out.filter(x=>x.date>n).sort((a,b)=>a.date-b.date)[0];};

  function injectCSS(){if(document.getElementById('k-enh-style'))return;const s=document.createElement('style');s.id='k-enh-style';s.textContent='.k-enh{margin-top:12px;padding-top:12px;border-top:1px solid var(--line)}.k-enh-row{display:flex;justify-content:space-between;gap:8px;align-items:center;margin:7px 0}.k-enh-row input{max-width:150px}.k-enh-small{font-size:11.5px;color:var(--muted)}.k-enh-save{background:var(--gold);color:#171310;border:0;border-radius:8px;padding:8px 12px;font-weight:600;cursor:pointer}';document.head.appendChild(s);}
  function injectObligationsEditor(){const home=document.getElementById('page-home');if(!home||document.getElementById('kObligEditor'))return;const sec=document.createElement('section');sec.id='kObligEditor';sec.innerHTML='<h2>Обязательные платежи</h2><div class="hint">Суммы можно менять в любое время. Изменения сразу участвуют в расчёте «Можно потратить сегодня».</div><div id="kObligRows"></div><button id="kObligSave" class="k-enh-save">Сохранить суммы</button>';home.appendChild(sec);renderObligations();document.getElementById('kObligSave').onclick=()=>{const rows=[...document.querySelectorAll('[data-oblig-id]')];write(OBL_KEY,obligations().map(o=>{const el=rows.find(x=>x.dataset.obligId===o.id);return {...o,amount:Math.max(0,Number(el?.value)||0)};}));renderObligations();renderHero();};}
  function renderObligations(){const box=document.getElementById('kObligRows');if(!box)return;box.innerHTML=obligations().map(o=>`<div class="k-enh-row"><span>${o.name}</span><input data-oblig-id="${o.id}" type="number" min="0" value="${o.amount}"></div>`).join('');}

  function currentCalc(){const n=today(),y=n.getFullYear(),m=n.getMonth(),mt=txs().filter(t=>{const d=dateOnly(t.date);return d.getFullYear()===y&&d.getMonth()===m&&!future(t.date);});const income=mt.filter(isIncome).reduce((s,t)=>s+Number(t.amount||0),0),expense=mt.filter(isExpense).reduce((s,t)=>s+Number(t.amount||0),0),saving=mt.filter(isSaving).reduce((s,t)=>s+Number(t.amount||0),0),balance=income-expense-saving,paidObl=mt.filter(t=>isExpense(t)&&t.category==='Обязательные платежи').reduce((s,t)=>s+Number(t.amount||0),0),oblLeft=Math.max(0,obligations().reduce((s,o)=>s+Number(o.amount||0),0)-paidObl),paidDebt=mt.filter(t=>isExpense(t)&&t.category==='Долг').reduce((s,t)=>s+Number(t.amount||0),0),debtMonthly=typeof DEBT!=='undefined'?Number(DEBT.monthly||0):0,debtTotal=typeof DEBT!=='undefined'?Number(DEBT.total||0):0,debtPaidAll=txs().filter(t=>isExpense(t)&&t.category==='Долг').reduce((s,t)=>s+Number(t.amount||0),0),debtLeft=Math.max(0,Math.min(debtMonthly,Math.max(0,debtTotal-debtPaidAll))-paidDebt),goalPlan=typeof GOALS!=='undefined'?GOALS.reduce((s,g)=>s+Number(g.monthly||0),0):0,saved=mt.filter(isSaving).reduce((s,t)=>s+Number(t.amount||0),0),goalLeft=Math.max(0,goalPlan-saved),plans=read(PLANS_KEY,[]).filter(p=>p.date>=iso(n)&&p.date<=iso(new Date(n.getFullYear(),n.getMonth()+1,10))),planLeft=plans.reduce((s,p)=>s+Number(p.amount||0),0),next=nextSalary(),days=next?Math.max(1,Math.ceil((next.date-n)/86400000)):1;return{balance,oblLeft,debtLeft,goalLeft,planLeft,days,next,reserve:oblLeft+debtLeft+goalLeft+planLeft};}
  function renderHero(){const h=document.getElementById('heroDaily');if(!h)return;const c=currentCalc(),mode=localStorage.getItem(MODE_KEY)||'reserved',daily=mode==='free'?Math.max(0,c.balance/c.days):Math.max(0,(c.balance-c.reserve)/c.days);h.textContent=fmt(daily);h.className='hero-value'+(daily<=0?' zero':'');const sub=document.getElementById('heroSub');if(sub)sub.textContent=c.next?`${c.days} ${c.days===1?'день':c.days<5?'дня':'дней'} до следующей выплаты · ${c.next.date.toLocaleDateString('ru-RU',{day:'2-digit',month:'long'})} · +${fmt(c.next.amount)}`:'Нет ближайшей выплаты';const box=document.getElementById('heroReserves');if(box)box.innerHTML=`<div class="reserve-row"><span>Обязательные платежи</span><span class="reserve-amt">${fmt(c.oblLeft)}</span></div><div class="reserve-row"><span>Долг</span><span class="reserve-amt">${fmt(c.debtLeft)}</span></div><div class="reserve-row"><span>Цели</span><span class="reserve-amt">${fmt(c.goalLeft)}</span></div><div class="reserve-row"><span>Плановые траты / должен</span><span class="reserve-amt">${fmt(c.planLeft)}</span></div>`;}

  function archiveAllMonths(){const reports=read(REPORTS_KEY,{}),keys=new Set(txs().map(t=>String(t.date).slice(0,7)).filter(Boolean));keys.add(iso(today()).slice(0,7));keys.forEach(k=>{const [y,m0]=k.split('-').map(Number),m=m0-1,mt=txs().filter(t=>{const d=dateOnly(t.date);return d.getFullYear()===y&&d.getMonth()===m&&!future(t.date);}),income=mt.filter(isIncome).reduce((s,t)=>s+Number(t.amount||0),0),expense=mt.filter(isExpense).reduce((s,t)=>s+Number(t.amount||0),0),saving=mt.filter(isSaving).reduce((s,t)=>s+Number(t.amount||0),0);reports[k]={year:y,month:m,income,expense,saving,balance:income-expense-saving,updatedAt:new Date().toISOString()};});write(REPORTS_KEY,reports);}
  function refreshArchive(){const list=document.getElementById('kReportsList');if(!list)return;const r=read(REPORTS_KEY,{}),keys=Object.keys(r).sort().reverse();list.innerHTML=keys.length?keys.map(k=>`<div class="k-v4-item"><div class="k-v4-row"><b>${k}</b><span>${fmt(r[k].balance)}</span></div><div class="k-v4-muted">Доход ${fmt(r[k].income)} · Расходы ${fmt(r[k].expense)} · Накопления ${fmt(r[k].saving)}</div></div>`).join(''):'<div class="k-v4-muted">Нет сохранённых месяцев.</div>';}
  function boot(){injectCSS();injectObligationsEditor();const run=()=>{archiveAllMonths();renderHero();refreshArchive();};setTimeout(run,1100);setInterval(run,30000);window.addEventListener('online',run);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();