/* KOPEYKA FINANCE CORE v1 — single source of truth for money */
(function(){
'use strict';
const n=v=>Number(v)||0;
const rub=k=>Math.round(n(k)/100);
const kop=r=>Math.round(n(r)*100);
const today=()=>todayStr();
const inRange=(d,s,e)=>d>=s&&d<=e;
function actualManualIncome(s,e){return (STATE.income||[]).filter(i=>inRange(i.date,s,e)&&i.status==='actual').reduce((a,i)=>a+n(i.amount),0)}
function expectedManualIncome(s,e){return (STATE.income||[]).filter(i=>inRange(i.date,s,e)&&i.status!=='actual').reduce((a,i)=>a+n(i.amount),0)}
function expenses(s,e){let ar=0,pr=0,ao=0,po=0;(STATE.expenses||[]).forEach(x=>{if(!inRange(x.date,s,e))return;const a=n(x.amount);if(x.mandatory){x.date<=today()?ao+=a:po+=a}else{x.date<=today()?ar+=a:pr+=a}});(STATE.recurring||[]).filter(r=>r.active).forEach(r=>{occurrencesInRange(r,s,e).forEach(d=>{const a=n(r.amount);if(d<=today())ao+=a;else po+=a})});return{ar,pr,ao,po}}
function debtList(){return Array.isArray(STATE.debts)?STATE.debts:[]}
function debtsFor(s,e){let actual=0,planned=0;debtList().forEach(d=>{const rem=Math.max(0,n(d.amount)-n(d.paid));if(!rem)return;const due=d.dueDate||e;if(d.paidDate&&d.paidDate<=e)actual+=Math.min(n(d.paid),n(d.amount));if(!d.paidDate&&due>=s&&due<=e)planned+=rem});return{actual,planned}}
function reserveDue(s,e,totalIncome){let due=0;const rows=[];(STATE.reserves||[]).filter(r=>r.active).forEach(r=>{let x=0;if(r.method==='fixed'){x=n(r.fixedAmount)}else if(r.method==='percent'){x=totalIncome*n(r.percent)/100}else if(r.method==='target'&&r.targetDate){const rem=Math.max(0,n(r.target)-n(r.saved));if(rem>0&&r.targetDate>=today()){const days=Math.max(1,diffDays(today(),r.targetDate));const end=e<r.targetDate?e:r.targetDate;if(end>=today())x=rem*(diffDays(today(),end)+1)/days}}const deposited=(STATE.reserveOps||[]).filter(o=>o.reserveId===r.id&&o.type==='deposit'&&inRange(o.date,s,e)).reduce((a,o)=>a+n(o.amount),0);x=Math.max(0,Math.round(x)-deposited);due+=x;rows.push({reserve:r,need:x})});return{due,rows}}
function coreSummary(state,s,e){const ai=actualManualIncome(s,e),ei=expectedManualIncome(s,e),ex=expenses(s,e),db=debtsFor(s,e),rv=reserveDue(s,e,ai+ei);const base=n(state.settings&&state.settings.currentBalance);let reserveDeposits=0,reserveWithdrawals=0;(state.reserveOps||[]).forEach(o=>{if(!inRange(o.date,s,e))return;if(o.type==='deposit'&&o.date<=today())reserveDeposits+=n(o.amount);if(o.type==='withdraw'&&o.date<=today())reserveWithdrawals+=n(o.amount)});const cashNow=base+ai-ex.ar-ex.ao-reserveDeposits+reserveWithdrawals;const futureCash=cashNow+ei-ex.pr-ex.po-db.planned-rv0;const plannedReserve=Math.min(Math.max(0,cashNow+ei-ex.pr-ex.po-db.planned),rv.due);const endReserve=rv.due;const safePool=cashNow+ei-ex.pr-ex.po-db.planned-endReserve;const strictPool=cashNow-ex.pr-ex.po-db.planned-endReserve;const remaining=e<today()?0:diffDays(today()>s?today():s,e)+1;const noReserve=cashNow+ei-ex.pr-ex.po-db.planned;const safe=Math.max(0,safePool);const strict=Math.max(0,strictPool);const alloc=rv.rows.map(x=>({reserve:x.reserve,need:x.need,allocated:Math.min(x.need,Math.max(0,safePool)),deficit:Math.max(0,x.need-Math.max(0,safePool))}));return{periodStart:s,periodEnd:e,remainingDays:remaining,shiftsList:[],actualShiftIncome:0,expectedShiftIncome:0,actualManualIncome:ai,expectedManualIncome:ei,actualIncome:ai,expectedIncome:ei,totalIncome:ai+ei,actualRegular:ex.ar,plannedRegular:ex.pr,totalRegular:ex.ar+ex.pr,actualObligatory:ex.ao,plannedObligatory:ex.po,totalObligatory:ex.ao+ex.po,currentBalance:cashNow,availableNow:Math.max(0,cashNow),forecastBeforeReserves:Math.max(0,noReserve),forecastAfterReserves:safe,strictAvailable:strict,reservesNeeded:endReserve,reserveBreakdown:rv.rows,allocation,debtsDue:db.planned,debtsPaid:db.actual,noReserveLimit:remaining?Math.floor(Math.max(0,noReserve)/remaining):null,safeLimit:remaining?Math.floor(safe/remaining):null,strictLimit:remaining?Math.floor(strict/remaining):null,reserveDeposits,reserveWithdrawals};}
/* remove an accidental legacy variable if minifier encounters it */
const old=window.computePeriodSummary;window.computePeriodSummary=function(state,s,e){return coreSummary(state,s,e)};
window.getStrictAvailable=s=>Math.max(0,n(s&&s.currentBalance)-n(s&&s.plannedRegular)-n(s&&s.plannedObligatory)-n(s&&s.reservesNeeded)-n(s&&s.debtsDue));
window.financeCore=coreSummary;

function debtModal(id){const d=id?debtList().find(x=>x.id===id):{name:'',amount:0,paid:0,dueDate:today(),comment:''};let h='<div class="modal">'+modalHeader(id?'Изменить долг':'Добавить «Должен»');h+=field('text','dName','Кому / за что',d.name,'Например: Иван — за ремонт');h+=field('number','dAmount','Сумма, ₽',rub(d.amount),'');h+=field('number','dPaid','Уже отдано, ₽',rub(d.paid),'');h+=field('date','dDue','Срок',d.dueDate||'','');h+=field('text','dComment','Комментарий',d.comment||'','');h+='<div class="modal-actions">'+(id?'<button class="btn btn-danger" data-debt-del>Удалить</button>':'')+'<button class="btn btn-primary btn-block" data-debt-save>Сохранить</button></div></div>';showModal(h);document.querySelector('[data-debt-save]').onclick=()=>{const x={id:id||uid(),name:document.getElementById('dName').value.trim()||'Должен',amount:kop(document.getElementById('dAmount').value),paid:kop(document.getElementById('dPaid').value),dueDate:document.getElementById('dDue').value||'',comment:document.getElementById('dComment').value.trim()};if(id)Object.assign(d,x);else{STATE.debts=debtList();STATE.debts.push(x)}closeModal();persist();showToast('Долг сохранён')};if(id)document.querySelector('[data-debt-del]').onclick=()=>confirmDelete('Удалить долг?',()=>{STATE.debts=debtList().filter(x=>x.id!==id);closeModal();persist()})}
function renderReservesCore(){const {start,end}=currentPeriod(),s=computePeriodSummary(STATE,start,end);let h='<div class="grid2">';h+=statCard('Доступно сейчас',fmt(s.currentBalance),'после фактических операций',[],'');h+=statCard('Нужно отложить',fmt(s.reservesNeeded),'резервы этого периода',[],'');h+='</div>';h+='<div class="card"><div class="row"><span>Фактический доход</span><b class="pos">'+fmt(s.actualIncome)+'</b></div><div class="row"><span>Фактические расходы</span><b class="neg">−'+fmt(s.actualRegular+s.actualObligatory)+'</b></div><div class="row"><span>Долги</span><b class="neg">−'+fmt(s.debtsDue)+'</b></div><div class="row"><span>Можно тратить в день</span><b class="pos">'+(s.safeLimit==null?'—':fmt(s.safeLimit))+'</b></div></div>';
h+='<div class="section-title">Должен</div><div class="card">';const ds=debtList();if(!ds.length)h+=emptyState('Долгов пока нет','&#128176;');else ds.forEach(d=>{const rem=Math.max(0,n(d.amount)-n(d.paid));h+='<div class="item" data-debt="'+d.id+'"><div class="ico">&#128176;</div><div class="body"><div class="title">'+esc(d.name)+'</div><div class="sub">'+(d.dueDate?'до '+fmtDateHuman(d.dueDate):'без срока')+'</div></div><div class="amt">'+fmt(rem)+'</div></div>'});h+='<button class="btn btn-secondary btn-block" data-debt-add>+ Добавить долг</button></div>';
h+='<div class="section-title">Резервы</div>';if(!STATE.reserves.length)h+='<div class="card">'+emptyState('Резервов пока нет','&#128176;')+'</div>';else STATE.reserves.slice().sort((a,b)=>(a.priority||99)-(b.priority||99)).forEach(r=>{const pct=r.target>0?Math.min(100,Math.round(100*(r.saved||0)/r.target)):0;h+='<div class="card" data-open="reserve:'+r.id+'"><div class="row"><div style="font-weight:700">'+esc(r.name)+'</div><div>'+fmt(r.saved||0)+' / '+fmt(r.target||0)+'</div></div><div class="progress"><div style="width:'+pct+'%"></div></div><div class="faint" style="margin-top:6px">'+methodLabel(r)+'</div></div>'});document.getElementById('main').innerHTML=h;document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openReserveModal(el.dataset.open.slice(8)));document.querySelector('[data-debt-add]').onclick=()=>debtModal();document.querySelectorAll('[data-debt]').forEach(el=>el.onclick=()=>debtModal(el.dataset.debt))}
window.renderReserves=renderReservesCore;
/* Patch state migration once, without touching existing user data. */
if(!Array.isArray(STATE.debts)){STATE.debts=[];saveState()}
})();
