/* KOPEYKA FINANCE CORE v4 — one coherent model for income, spending, reserves and debts */
(function(){
'use strict';
const N=v=>Number(v)||0, rub=k=>Math.round(N(k)/100), kop=r=>Math.round(N(r)*100), today=()=>todayStr(), A=k=>Array.isArray(STATE[k])?STATE[k]:[], range=(d,s,e)=>d>=s&&d<=e;
function incomes(s,e){let actual=0,expected=0;A('income').forEach(i=>{if(!range(i.date,s,e))return;i.status==='actual'?actual+=N(i.amount):expected+=N(i.amount)});return{actual,expected}}
function expenses(s,e){let actual=0,future=0,actualMandatory=0,futureMandatory=0;A('expenses').forEach(x=>{if(!range(x.date,s,e))return;const a=N(x.amount);if(x.date<=today()){actual+=a;if(x.mandatory)actualMandatory+=a}else{future+=a;if(x.mandatory)futureMandatory+=a}});A('recurring').filter(x=>x.active).forEach(r=>{try{occurrencesInRange(r,s,e).forEach(d=>{const a=N(r.amount);if(d<=today()){actual+=a;if(r.mandatory)actualMandatory+=a}else{future+=a;if(r.mandatory)futureMandatory+=a}})}catch(_){}});return{actual,future,actualMandatory,futureMandatory}}
/* Debt is an obligation until explicitly paid. Paying it is the moment money leaves cash. */
function debts(s,e){let open=0,paid=0;A('debts').forEach(d=>{const total=N(d.amount),isPaid=d.status==='paid'||d.closed===true,paidAmount=Math.min(total,N(d.paidAmount??d.paid));if(isPaid){if(d.paidAt&&range(d.paidAt,s,e))paid+=paidAmount||total;return}const remaining=Math.max(0,total-paidAmount);if(remaining&&(!d.dueDate||range(d.dueDate,s,e)))open+=remaining});return{open,paid}}
function reserves(s,e,incomeTotal){let need=0,deposited=0,withdrawn=0;A('reserveOps').forEach(o=>{if(!range(o.date,s,e)||o.date>today())return;o.type==='deposit'?deposited+=N(o.amount):o.type==='withdraw'&&(withdrawn+=N(o.amount))});const rows=[];A('reserves').filter(r=>r.active).forEach(r=>{let required=0;if(r.method==='fixed')required=N(r.fixedAmount);else if(r.method==='percent')required=incomeTotal*N(r.percent)/100;else if(r.method==='target'&&r.targetDate){const left=Math.max(0,N(r.target)-N(r.saved));if(left&&r.targetDate>=today())required=left/Math.max(1,diffDays(today(),r.targetDate)+1)}const already=A('reserveOps').filter(o=>o.reserveId===r.id&&o.type==='deposit'&&o.date<=today()).reduce((a,o)=>a+N(o.amount),0);required=Math.max(0,Math.round(required)-already);need+=required;rows.push({reserve:r,need:required,deposited:already})});return{need,deposited,withdrawn,rows}}
function core(state,s,e){const inc=incomes(s,e),ex=expenses(s,e),debt=debts(s,e),rv=reserves(s,e,inc.actual+inc.expected),base=N(state.settings&&state.settings.currentBalance);/* Base balance is an opening balance, never overwritten by calculated totals. */const cash=base+inc.actual-ex.actual-debt.paid-rv.deposited+rv.withdrawn;const future=ex.future+debt.open+rv.need;const forecast=cash+inc.expected-future;const strict=cash-future;const start=today()>s?today():s,days=e<today()?0:Math.max(1,diffDays(start,e)+1);return{periodStart:s,periodEnd:e,remainingDays:days,shiftsList:[],actualShiftIncome:0,expectedShiftIncome:0,actualManualIncome:inc.actual,expectedManualIncome:inc.expected,actualIncome:inc.actual,expectedIncome:inc.expected,totalIncome:inc.actual+inc.expected,actualRegular:ex.actual-ex.actualMandatory,plannedRegular:ex.future-ex.futureMandatory,totalRegular:ex.actual+ex.future,actualObligatory:ex.actualMandatory,plannedObligatory:ex.futureMandatory,totalObligatory:ex.actualMandatory+ex.futureMandatory,currentBalance:cash,availableNow:Math.max(0,cash),forecastBeforeReserves:Math.max(0,cash+inc.expected-ex.future-debt.open),forecastAfterReserves:Math.max(0,forecast),strictAvailable:Math.max(0,strict),reservesNeeded:rv.need,reserveBreakdown:rv.rows,debtsDue:debt.open,debtsPaid:debt.paid,reserveDeposits:rv.deposited,reserveWithdrawals:rv.withdrawn,noReserveLimit:days?Math.floor(Math.max(0,cash+inc.expected-ex.future-debt.open)/days):0,safeLimit:days?Math.floor(Math.max(0,forecast)/days):0,strictLimit:days?Math.floor(Math.max(0,strict)/days):0}}
window.computePeriodSummary=core;window.financeCore=core;window.getStrictAvailable=s=>Math.max(0,N(s&&s.currentBalance)-N(s&&s.plannedRegular)-N(s&&s.plannedObligatory)-N(s&&s.reservesNeeded)-N(s&&s.debtsDue));
function debtModal(id){const d=id?A('debts').find(x=>x.id===id):{name:'',amount:0,dueDate:today(),comment:'',status:'open'};const closed=d.status==='paid'||d.closed===true;let h='<div class="modal">'+modalHeader(id?'Долг':'Добавить «Должен»');h+=field('text','dName','Кому / за что',d.name,'Например: Иван — за ремонт');h+=field('number','dAmount','Сумма, ₽',rub(d.amount),'');h+=field('date','dDue','Срок',d.dueDate||'','');h+=field('text','dComment','Комментарий',d.comment||'','');if(id)h+='<div class="faint" style="margin:4px 0 12px">'+(closed?'Погашен: деньги уже списаны.':'Не погашен: деньги ещё не списаны, но долг учитывается в плане.')+'</div>';h+='<div class="modal-actions">'+(id?'<button class="btn '+(closed?'btn-secondary':'btn-primary')+' btn-block" data-debt-toggle>'+(closed?'Вернуть долг в непогашенные':'Погасить долг')+'</button><button class="btn btn-danger" data-debt-del>Удалить</button>':'<button class="btn btn-primary btn-block" data-debt-save>Сохранить</button>')+'</div></div>';showModal(h);if(!id)document.querySelector('[data-debt-save]').onclick=()=>{if(!Array.isArray(STATE.debts))STATE.debts=[];STATE.debts.push({id:uid(),name:document.getElementById('dName').value.trim()||'Должен',amount:kop(document.getElementById('dAmount').value),paidAmount:0,status:'open',dueDate:document.getElementById('dDue').value||'',comment:document.getElementById('dComment').value.trim(),createdAt:today()});closeModal();persist();render()};if(id){document.querySelector('[data-debt-toggle]').onclick=()=>{if(closed){d.status='open';d.closed=false;d.paidAt=null;d.paidAmount=0}else{d.status='paid';d.closed=true;d.paidAt=today();d.paidAmount=N(d.amount)}closeModal();persist();render()};document.querySelector('[data-debt-del]').onclick=()=>confirmDelete('Удалить долг?',()=>{STATE.debts=A('debts').filter(x=>x.id!==id);closeModal();persist();render()})}}
function injectDebts(){if(window.ROUTE!=='reserves')return;const main=document.getElementById('main');if(!main||main.querySelector('[data-debt-section]'))return;const box=document.createElement('div');box.dataset.debtSection='1';box.innerHTML='<div class="section-title">Должен</div><div class="card"><div class="faint" style="margin-bottom:10px">Непогашенный долг — обязательство, но не уже потраченные деньги.</div><div data-debt-list></div><button class="btn btn-secondary btn-block" data-debt-add>+ Добавить «Должен»</button></div>';main.appendChild(box);const list=box.querySelector('[data-debt-list]');const ds=A('debts');if(!ds.length)list.innerHTML='<div class="faint" style="padding:8px 0 12px">Долгов пока нет</div>';ds.forEach(d=>{const closed=d.status==='paid'||d.closed===true,rem=Math.max(0,N(d.amount)-N(d.paidAmount||d.paid));const el=document.createElement('div');el.className='item';el.innerHTML='<div class="ico">'+(closed?'✓':'₽')+'</div><div class="body"><div class="title">'+esc(d.name||'Должен')+(closed?' <span class="pill off">погашен</span>':'')+'</div><div class="sub">'+(closed?'Погашен '+fmtDateHuman(d.paidAt):'Остаток '+fmt(rem)+(d.dueDate?' · до '+fmtDateHuman(d.dueDate):''))+'</div></div><div class="amt">'+fmt(closed?0:rem)+'</div>';el.onclick=()=>debtModal(d.id);list.appendChild(el)});box.querySelector('[data-debt-add]').onclick=()=>debtModal()}
window.openDebtModal=debtModal;window.injectDebtSection=injectDebts;const R=window.render;if(typeof R==='function'&&!R.__financeV4){window.render=function(){R.apply(this,arguments);setTimeout(injectDebts,0)};window.render.__financeV4=true}if(!Array.isArray(STATE.debts)){STATE.debts=[];saveState()}setTimeout(injectDebts,50);
})();
