/* KOPEYKA FINANCE CORE v2 — one deterministic money model */
(function(){
'use strict';
const n=v=>Number(v)||0, rub=k=>Math.round(n(k)/100), kop=r=>Math.round(n(r)*100);
const td=()=>todayStr(), inRange=(d,s,e)=>d>=s&&d<=e;
function ai(s,e){return (STATE.income||[]).filter(i=>inRange(i.date,s,e)&&i.status==='actual').reduce((a,i)=>a+n(i.amount),0)}
function ei(s,e){return (STATE.income||[]).filter(i=>inRange(i.date,s,e)&&i.status!=='actual').reduce((a,i)=>a+n(i.amount),0)}
function ex(s,e){let ar=0,pr=0,ao=0,po=0;(STATE.expenses||[]).forEach(x=>{if(!inRange(x.date,s,e))return;const a=n(x.amount);if(x.mandatory)x.date<=td()?ao+=a:po+=a;else x.date<=td()?ar+=a:pr+=a});(STATE.recurring||[]).filter(r=>r.active).forEach(r=>occurrencesInRange(r,s,e).forEach(d=>{const a=n(r.amount);d<=td()?ao+=a:po+=a}));return{ar,pr,ao,po}}
function debts(s,e){let due=0,paid=0;(STATE.debts||[]).forEach(d=>{const rem=Math.max(0,n(d.amount)-n(d.paid));if(rem<=0)return;const date=d.dueDate||e;if(date>=s&&date<=e)due+=rem;paid+=Math.min(n(d.paid),n(d.amount))});return{due,paid}}
function reserves(s,e,totalIncome){let due=0;const rows=[];(STATE.reserves||[]).filter(r=>r.active).forEach(r=>{let need=0;if(r.method==='fixed')need=n(r.fixedAmount);else if(r.method==='percent')need=totalIncome*n(r.percent)/100;else if(r.method==='target'&&r.targetDate){const rem=Math.max(0,n(r.target)-n(r.saved));if(rem>0&&r.targetDate>=td()){const end=e<r.targetDate?e:r.targetDate;if(end>=td()){const totalDays=Math.max(1,diffDays(td(),r.targetDate)+1);need=rem*(diffDays(td(),end)+1)/totalDays}}}const deposited=(STATE.reserveOps||[]).filter(o=>o.reserveId===r.id&&o.type==='deposit'&&inRange(o.date,s,e)).reduce((a,o)=>a+n(o.amount),0);need=Math.max(0,Math.round(need)-deposited);due+=need;rows.push({reserve:r,need})});return{due,rows}}
function core(state,s,e){const actualIncome=ai(s,e),expectedIncome=ei(s,e),x=ex(s,e),d=debts(s,e),r=reserves(s,e,actualIncome+expectedIncome);const base=n(state.settings?.currentBalance);let dep=0,wd=0;(state.reserveOps||[]).forEach(o=>{if(!inRange(o.date,s,e)||o.date>td())return;if(o.type==='deposit')dep+=n(o.amount);if(o.type==='withdraw')wd+=n(o.amount)});const cashNow=base+actualIncome-x.ar-x.ao-dep+wd;const futureExpenses=x.pr+x.po;const noReservePool=cashNow+expectedIncome-futureExpenses-d.due;const safePool=noReservePool-r.due;const strictPool=cashNow-futureExpenses-d.due-r.due;const start=td()>s?td():s;const days=e<td()?0:diffDays(start,e)+1;const allocation=r.rows.map(z=>{const a=Math.min(z.need,Math.max(0,safePool));return{reserve:z.reserve,need:z.need,allocated:a,deficit:Math.max(0,z.need-a)}});return{periodStart:s,periodEnd:e,remainingDays:days,shiftsList:[],actualShiftIncome:0,expectedShiftIncome:0,actualManualIncome:actualIncome,expectedManualIncome:expectedIncome,actualIncome,expectedIncome,totalIncome:actualIncome+expectedIncome,actualRegular:x.ar,plannedRegular:x.pr,totalRegular:x.ar+x.pr,actualObligatory:x.ao,plannedObligatory:x.po,totalObligatory:x.ao+x.po,currentBalance:cashNow,availableNow:cashNow,forecastBeforeReserves:noReservePool,forecastAfterReserves:safePool,strictAvailable:strictPool,reservesNeeded:r.due,reserveBreakdown:r.rows,allocation,debtsDue:d.due,debtsPaid:d.paid,reserveDeposits:dep,reserveWithdrawals:wd,noReserveLimit:days?Math.floor(noReservePool/days):null,safeLimit:days?Math.floor(safePool/days):null,strictLimit:days?Math.floor(strictPool/days):null}}
window.computePeriodSummary=core;window.financeCore=core;window.getStrictAvailable=s=>Math.max(0,n(s?.currentBalance)-n(s?.plannedRegular)-n(s?.plannedObligatory)-n(s?.reservesNeeded)-n(s?.debtsDue));
function debtModal(id){const d=id?(STATE.debts||[]).find(x=>x.id===id):{name:'',amount:0,paid:0,dueDate:td(),comment:''};let h='<div class="modal">'+modalHeader(id?'Изменить «Должен»':'Добавить «Должен»');h+=field('text','dName','Кому / за что',d.name,'Например: Иван — за ремонт');h+=field('number','dAmount','Сумма, ₽',rub(d.amount),'');h+=field('number','dPaid','Уже отдано, ₽',rub(d.paid),'');h+=field('date','dDue','Срок',d.dueDate||'','');h+=field('text','dComment','Комментарий',d.comment||'','');h+='<div class="modal-actions">'+(id?'<button class="btn btn-danger" data-debt-del>Удалить</button>':'')+'<button class="btn btn-primary btn-block" data-debt-save>Сохранить</button></div></div>';showModal(h);document.querySelector('[data-debt-save]').onclick=()=>{const x={id:id||uid(),name:document.getElementById('dName').value.trim()||'Должен',amount:kop(document.getElementById('dAmount').value),paid:kop(document.getElementById('dPaid').value),dueDate:document.getElementById('dDue').value||'',comment:document.getElementById('dComment').value.trim()};if(id)Object.assign(d,x);else{if(!Array.isArray(STATE.debts))STATE.debts=[];STATE.debts.push(x)}closeModal();persist();showToast('Долг сохранён')};if(id)document.querySelector('[data-debt-del]').onclick=()=>confirmDelete('Удалить долг?',()=>{STATE.debts=(STATE.debts||[]).filter(x=>x.id!==id);closeModal();persist()})}
function renderReservesCore(){const {start,end}=currentPeriod(),s=core(STATE,start,end);let h='<div class="grid2">';h+=statCard('Доступно сейчас',fmt(s.currentBalance),'реальные деньги',[],'');h+=statCard('Можно тратить в день',s.safeLimit==null?'—':fmt(Math.max(0,s.safeLimit)),'после будущих обязательств и резервов',[],'');h+='</div><div class="card"><div class="row"><span>Получено вручную</span><b class="pos">'+fmt(s.actualIncome)+'</b></div><div class="row"><span>Расходы уже сделаны</span><b class="neg">−'+fmt(s.actualRegular+s.actualObligatory)+'</b></div><div class="row"><span>Резерв уже отложен</span><b class="neg">−'+fmt(s.reserveDeposits)+'</b></div><div class="row"><span>Ожидается</span><b class="pos">+'+fmt(s.expectedIncome)+'</b></div><div class="row"><span>Будущие расходы</span><b class="neg">−'+fmt(s.plannedRegular+s.plannedObligatory)+'</b></div><div class="row"><span>Должен</span><b class="neg">−'+fmt(s.debtsDue)+'</b></div><div class="row"><span>Резервы</span><b class="neg">−'+fmt(s.reservesNeeded)+'</b></div><div class="row" style="margin-top:8px"><strong>Остаток после плана</strong><strong>'+fmt(Math.max(0,s.forecastAfterReserves))+'</strong></div></div>';
h+='<div class="section-title">Должен</div><div class="card">';const ds=STATE.debts||[];if(!ds.length)h+=emptyState('Долгов пока нет','&#128176;');else ds.forEach(d=>{const rem=Math.max(0,n(d.amount)-n(d.paid));h+='<div class="item" data-debt="'+d.id+'"><div class="ico">&#128176;</div><div class="body"><div class="title">'+esc(d.name)+'</div><div class="sub">'+(d.dueDate?'до '+fmtDateHuman(d.dueDate):'без срока')+'</div></div><div class="amt">'+fmt(rem)+'</div></div>'});h+='<button class="btn btn-secondary btn-block" data-debt-add>+ Добавить долг</button></div>';
h+='<div class="section-title">Резервы</div>';if(!STATE.reserves.length)h+='<div class="card">'+emptyState('Резервов пока нет','&#128176;')+'</div>';else STATE.reserves.slice().sort((a,b)=>(a.priority||99)-(b.priority||99)).forEach(r=>{const pct=r.target>0?Math.min(100,Math.round(100*(r.saved||0)/r.target)):0;h+='<div class="card" data-open="reserve:'+r.id+'" style="cursor:pointer"><div class="row"><div style="font-weight:700">'+esc(r.name)+'</div><div>'+fmt(r.saved||0)+' / '+fmt(r.target||0)+'</div></div><div class="progress"><div style="width:'+pct+'%"></div></div><div class="faint" style="margin-top:6px">'+methodLabel(r)+'</div></div>'});document.getElementById('main').innerHTML=h;document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openReserveModal(el.dataset.open.slice(8)));document.querySelector('[data-debt-add]').onclick=()=>debtModal();document.querySelectorAll('[data-debt]').forEach(el=>el.onclick=()=>debtModal(el.dataset.debt))}
window.renderReserves=renderReservesCore;if(!Array.isArray(STATE.debts)){STATE.debts=[];saveState()}
})();
