/* KOPEYKA CLOUD SYNC v7 — cross-browser state + migration from previous cloud keys */
(function(){
'use strict';
const SB_URL='https://cqslrfphsjllhltsvvuq.supabase.co';
const SB_KEY='sb_publishable_cM_XCycYRFLIc6qEqlH83Q_5XY6kPzG';
const H={apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json'};
const META='__state_v3__',OLD_META='__state_v2__';
const n=v=>Number(v)||0,today=()=>new Date().toISOString().slice(0,10);
const original=window.computePeriodSummary;let cloudId=null,cloudReady=false,syncing=false,lastCloud='';
function incomeFor(start,end){let actual=0,expected=0;(window.STATE?.income||[]).forEach(i=>{if(!i||i.date<start||i.date>end)return;const a=n(i.amount);if(['expected','planned','forecast'].includes(i.status))expected+=a;else actual+=a});return{actual,expected,total:actual+expected}}
function correctedSummary(state,start,end){const base=original?original(state,start,end):{},inc=incomeFor(start,end),t=today();let ar=0,pr=0,ao=0,po=0;(state.expenses||[]).forEach(e=>{if(!e||e.date<start||e.date>end)return;const a=n(e.amount);if(e.mandatory)e.date>t?po+=a:ao+=a;else e.date>t?pr+=a:ar+=a});(state.recurring||[]).filter(r=>r.active).forEach(r=>{try{occurrencesInRange(r,start,end).forEach(d=>{const a=n(r.amount);d>t?po+=a:ao+=a})}catch(_){}});let reservesNeeded=0;(state.reserves||[]).filter(r=>r.active).forEach(r=>{try{reservesNeeded+=n(reserveRawNeed(r,start,end,inc.total))}catch(_){}});const balance=n(state.settings?.currentBalance),available=Math.max(0,balance+inc.actual-ar-ao),forecast=Math.max(0,balance+inc.actual+inc.expected-ar-ao-pr-po),safe=Math.max(0,forecast-reservesNeeded),strict=Math.max(0,balance+inc.actual-ar-ao-pr-po-reservesNeeded),remaining=Math.max(1,diffDays(t>start?t:start,end)+1);return Object.assign({},base,{periodStart:start,periodEnd:end,shiftsList:[],actualShiftIncome:0,expectedShiftIncome:0,actualManualIncome:inc.actual,expectedManualIncome:inc.expected,actualIncome:inc.actual,expectedIncome:inc.expected,totalIncome:inc.total,currentBalance:balance,availableNow:available,forecastBeforeReserves:forecast,forecastAfterReserves:safe,strictAvailable:strict,noReserveLimit:Math.round(forecast/remaining),safeLimit:Math.round(safe/remaining),strictLimit:Math.round(strict/remaining),actualRegular:ar,plannedRegular:pr,totalRegular:ar+pr,actualObligatory:ao,plannedObligatory:po,totalObligatory:ao+po,reservesNeeded})}
window.computePeriodSummary=correctedSummary;window.getStrictAvailable=s=>Math.max(0,n(s?.currentBalance)+n(s?.actualIncome)-n(s?.actualRegular)-n(s?.actualObligatory)-n(s?.plannedRegular)-n(s?.plannedObligatory)-n(s?.reservesNeeded));try{window.SHIFT_RATE=0;window.MONTHLY_INCOME=0}catch(_){}
function cloudStatus(ok,msg){window.cloudOnline=!!ok;const d=document.getElementById('syncDot'),x=document.getElementById('syncText');if(d)d.className='sync-dot '+(ok?'online':'offline');if(x)x.textContent=msg||(ok?'в облаке':'только локально')}
async function getRows(category){const u=SB_URL+'/rest/v1/transactions?select=id,date,type,category,amount,shift,comment&category=eq.'+encodeURIComponent(category)+'&order=id.desc&limit=10';const r=await fetch(u,{headers:H,cache:'no-store'});if(!r.ok)throw Error('Supabase GET '+r.status);return await r.json()}
async function cloudGet(){const rows=[...(await getRows(META)),...(await getRows(OLD_META))];let best=null,bestTime=-1;for(const row of rows){try{const obj=JSON.parse(row.comment||'{}'),t=n(obj.updatedAt);if(obj.state&&t>=bestTime){best={row,state:obj.state,updatedAt:t};bestTime=t}}catch(_){}}return best}
async function cloudPut(force){if(!window.STATE||syncing)return;const json=JSON.stringify(STATE);if(!force&&json===lastCloud)return;syncing=true;try{const payload={date:today(),type:'Meta',category:META,amount:0,shift:'',comment:JSON.stringify({version:7,state:JSON.parse(json),updatedAt:Date.now()})};let r;if(cloudId)r=await fetch(SB_URL+'/rest/v1/transactions?id=eq.'+encodeURIComponent(cloudId),{method:'PATCH',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(payload)});else r=await fetch(SB_URL+'/rest/v1/transactions',{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw Error('Supabase WRITE '+r.status);const rows=await r.json();if(rows[0])cloudId=rows[0].id;lastCloud=json;cloudStatus(true,'в облаке')}catch(e){console.warn('Cloud sync:',e);cloudStatus(false,'ошибка облака')}finally{syncing=false}}
function isUserDataEmpty(s){if(!s||typeof s!=='object')return true;for(const k of ['income','expenses','reserves','recurring','debts','reserveOps'])if(Array.isArray(s[k])&&s[k].length)return false;const q=s.settings||{};return n(q.currentBalance)===0&&n(s.startBalance)===0}
async function cloudLoad(){try{const remote=await cloudGet();cloudStatus(true,remote?'в облаке':'облако пустое');if(remote){cloudId=remote.row.id;const localEmpty=isUserDataEmpty(STATE);/* A cloud snapshot is authoritative for a fresh browser. */if(localEmpty){STATE=remote.state;if(typeof saveState==='function')saveState();else try{localStorage.setItem('kopeyka_state',JSON.stringify(STATE))}catch(_){}}/* Migrate old __state_v2__ row to current key on next write. */lastCloud=JSON.stringify(STATE);if(localEmpty)setTimeout(()=>cloudPut(true),200)}else lastCloud=JSON.stringify(STATE);cloudReady=true;if(typeof render==='function')render()}catch(e){cloudStatus(false,'ошибка облака');cloudReady=true;lastCloud=JSON.stringify(STATE);console.warn('Cloud unavailable:',e)}}
function hookPersistence(){for(const name of ['saveState','persist']){const fn=window[name];if(typeof fn!=='function'||fn.__cloudV7)return;window[name]=function(){const r=fn.apply(this,arguments);setTimeout(()=>cloudPut(true),50);return r};window[name].__cloudV7=true}}
setInterval(()=>{if(cloudReady&&window.STATE){hookPersistence();const j=JSON.stringify(STATE);if(j!==lastCloud)cloudPut(false)}},1000);window.addEventListener('online',()=>cloudPut(true));function boot(){if(window.STATE){hookPersistence();cloudLoad()}else setTimeout(boot,100)}boot();
})();
