/* Копейка — layout + financial safety layer */
(function(){
'use strict';
const num=v=>Number(v)||0;
const fmt=n=>Math.round(num(n)).toLocaleString('ru-RU')+' ₽';
function period(){try{return typeof currentPeriod==='function'?currentPeriod():{start:'0000-01-01',end:'9999-12-31'}}catch(_){return{start:'0000-01-01',end:'9999-12-31'}}}
function manualIncome(start,end){const list=Array.isArray(window.STATE?.income)?STATE.income:[];let actual=0,planned=0;list.forEach(i=>{if(!i||i.date<start||i.date>end)return;const a=num(i.amount);if(['expected','planned','forecast'].includes(i.status))planned+=a;else actual+=a});return{actual,planned,total:actual+planned}}
function summary(start,end){const inc=manualIncome(start,end),t=new Date().toISOString().slice(0,10);let ar=0,pr=0,ao=0,po=0;const expenses=Array.isArray(window.STATE?.expenses)?STATE.expenses:[];expenses.forEach(e=>{if(!e||e.date<start||e.date>end)return;const a=num(e.amount),future=e.date>t;if(e.mandatory)future?po+=a:ao+=a;else future?pr+=a:ar+=a});const recurring=Array.isArray(window.STATE?.recurring)?STATE.recurring:[];recurring.filter(r=>r.active).forEach(r=>{try{occurrencesInRange(r,start,end).forEach(dt=>{const a=num(r.amount);dt>t?po+=a:ao+=a})}catch(_){}});const balance=num(window.STATE?.settings?.currentBalance);const reserves=Array.isArray(window.STATE?.reserves)?STATE.reserves.filter(r=>r.active).reduce((s,r)=>{try{return s+num(reserveRawNeed(r,start,end,inc.total))}catch(_){return s}},0):0;const spend=Math.max(0,balance+inc.actual-ar-ao),forecast=Math.max(0,balance+inc.actual+inc.planned-ar-ao-pr-po),strict=Math.max(0,balance+inc.actual-ar-ao-pr-po-reserves);const days=Math.max(1,Math.ceil((new Date(end)-new Date(t>start?t:start))/86400000)+1);return{actualIncome:inc.actual,expectedIncome:inc.planned,totalIncome:inc.total,currentBalance:balance,availableNow:spend,forecastAfterReserves:Math.max(0,forecast-reserves),strictAvailable:strict,safeLimit:Math.round(Math.max(0,forecast-reserves)/days),strictLimit:Math.round(strict/days),actualRegular:ar,plannedRegular:pr,actualObligatory:ao,plannedObligatory:po,reservesNeeded:reserves,actualShiftIncome:0,expectedShiftIncome:0,shiftsList:[]}}
window.computePeriodSummary=summary;
window.getStrictAvailable=s=>Math.max(0,num(s?.currentBalance)+num(s?.actualIncome)-num(s?.actualRegular)-num(s?.actualObligatory)-num(s?.plannedRegular)-num(s?.plannedObligatory)-num(s?.reservesNeeded));
window.renderIncome=function(){const p=period(),s=summary(p.start,p.end),list=(Array.isArray(STATE.income)?STATE.income:[]).filter(i=>i.date>=p.start&&i.date<=p.end).sort((a,b)=>String(b.date).localeCompare(String(a.date)));let h='<div class="grid2">';h+=statCard('Получено',fmt(s.actualIncome),'введено вручную');h+=statCard('Ожидается',fmt(s.expectedIncome),'введено вручную');h+='</div><div class="card" style="text-align:center"><div class="label">Доход за период</div><div class="mid-number">'+fmt(s.totalIncome)+'</div></div><div class="section-title">Введённый доход</div><div class="card">';if(!list.length)h+=emptyState('Доходов пока нет.','&#128176;');else list.forEach(i=>h+=itemRow('&#128181;',i.title||'Доход',fmtDateHuman(i.date)+' · '+(['expected','planned','forecast'].includes(i.status)?'ожидается':'получено'),fmt(i.amount),'income:'+i.id));h+='</div>';document.getElementById('main').innerHTML=h;bindListClicks()};
/* Never invent income from shifts. */
try{window.SHIFT_RATE=0;window.MONTHLY_INCOME=0}catch(_){ }
/* Mobile navigation: stable five-column layout with safe-area support. */
const css=document.createElement('style');css.textContent=`@media(max-width:899px){#main{padding-left:12px!important;padding-right:12px!important;padding-bottom:calc(88px + env(safe-area-inset-bottom,0px))!important}.bottomnav{display:flex!important;left:0!important;right:0!important;bottom:0!important;width:100%!important;height:auto!important;min-height:64px!important;padding:6px 4px calc(6px + env(safe-area-inset-bottom,0px))!important;gap:2px!important;justify-content:space-between!important;align-items:stretch!important;overflow:hidden!important}.navbtn{box-sizing:border-box!important;flex:1 1 0!important;width:auto!important;min-width:0!important;max-width:none!important;padding:5px 2px!important;gap:3px!important;font-size:10px!important;line-height:1.05!important;white-space:nowrap!important;overflow:hidden!important}.navbtn svg{width:21px!important;height:21px!important;flex:none!important}.navbtn span{display:block!important;max-width:100%!important;overflow:hidden!important;text-overflow:ellipsis!important}.fab{bottom:calc(78px + env(safe-area-inset-bottom,0px))!important}.toast{bottom:calc(82px + env(safe-area-inset-bottom,0px))!important}.card{padding:16px!important}.big-number{font-size:34px!important}.mid-number{font-size:20px!important}.item .amt{font-size:13px!important;min-width:0!important}@media(max-width:370px){.navbtn{font-size:8.5px!important;padding-left:1px!important;padding-right:1px!important}.navbtn svg{width:19px!important;height:19px!important}.card{padding:14px!important}}}`;document.head.appendChild(css);
})();
