/* KOPEYKA FIX CORE v6 — reliable cross-browser Supabase sync */
(function(){
'use strict';
const SB_URL='https://cqslrfphsjllhltsvvuq.supabase.co';
const SB_KEY='sb_publishable_cM_XCycYRFLIc6qEqlH83Q_5XY6kPzG';
const H={apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json'};
const META='__state_v3__';
const n=v=>Number(v)||0;
const today=()=>new Date().toISOString().slice(0,10);
const original=window.computePeriodSummary;
let cloudId=null,cloudReady=false,syncing=false,lastCloud='';
function incomeFor(start,end){let actual=0,expected=0;(window.STATE?.income||[]).forEach(i=>{if(!i||i.date<start||i.date>end)return;const a=n(i.amount);if(['expected','planned','forecast'].includes(i.status))expected+=a;else actual+=a});return{actual,expected,total:actual+expected}}
function correctedSummary(state,start,end){const base=original?original(state,start,end):{};const inc=incomeFor(start,end),t=today();let ar=0,pr=0,ao=0,po=0;(state.expenses||[]).forEach(e=>{if(!e||e.date<start||e.date>end)return;const a=n(e.amount);if(e.mandatory)e.date>t?po+=a:ao+=a;else e.date>t?pr+=a:ar+=a});(state.recurring||[]).filter(r=>r.active).forEach(r=>{try{occurrencesInRange(r,start,end).forEach(d=>{const a=n(r.amount);d>t?po+=a:ao+=a})}catch(_){}});let reservesNeeded=0;(state.reserves||[]).filter(r=>r.active).forEach(r=>{try{reservesNeeded+=n(reserveRawNeed(r,start,end,inc.total))}catch(_){}});const balance=n(state.settings?.currentBalance);const available=Math.max(0,balance+inc.actual-ar-ao);const forecast=Math.max(0,balance+inc.actual+inc.expected-ar-ao-pr-po);const safe=Math.max(0,forecast-reservesNeeded);const strict=Math.max(0,balance+inc.actual-ar-ao-pr-po-reservesNeeded);const remaining=Math.max(1,diffDays(t>start?t:start,end)+1);return Object.assign({},base,{periodStart:start,periodEnd:end,shiftsList:[],actualShiftIncome:0,expectedShiftIncome:0,actualManualIncome:inc.actual,expectedManualIncome:inc.expected,actualIncome:inc.actual,expectedIncome:inc.expected,totalIncome:inc.total,currentBalance:balance,availableNow:available,forecastBeforeReserves:forecast,forecastAfterReserves:safe,strictAvailable:strict,noReserveLimit:Math.round(forecast/remaining),safeLimit:Math.round(safe/remaining),strictLimit:Math.round(strict/remaining),actualRegular:ar,plannedRegular:pr,totalRegular:ar+pr,actualObligatory:ao,plannedObligatory:po,totalObligatory:ao+po,reservesNeeded})}
window.computePeriodSummary=correctedSummary;window.getStrictAvailable=s=>Math.max(0,n(s?.currentBalance)+n(s?.actualIncome)-n(s?.actualRegular)-n(s?.actualObligatory)-n(s?.plannedRegular)-n(s?.plannedObligatory)-n(s?.reservesNeeded));
try{window.SHIFT_RATE=0;window.MONTHLY_INCOME=0}catch(_){}
const st=document.createElement('style');st.textContent=`@media(max-width:899px){#main{padding:14px 12px calc(94px + env(safe-area-inset-bottom,0px))!important}.bottomnav{position:fixed!important;left:0!important;right:0!important;bottom:0!important;width:100%!important;z-index:100!important;display:flex!important;justify-content:space-between!important;align-items:stretch!important;gap:2px!important;padding:5px 3px calc(5px + env(safe-area-inset-bottom,0px))!important;min-height:66px!important;overflow:hidden!important}.navbtn{box-sizing:border-box!important;flex:1 1 0!important;width:0!important;min-width:0!important;max-width:none!important;padding:5px 2px!important;font-size:clamp(8.5px,2.65vw,10.5px)!important;line-height:1.05!important;white-space:nowrap!important;overflow:hidden!important}.navbtn span{min-width:0!important;max-width:100%!important;overflow:hidden!important;text-overflow:ellipsis!important}.fab{bottom:calc(76px + env(safe-area-inset-bottom,0px))!important}.toast{bottom:calc(82px + env(safe-area-inset-bottom,0px))!important}.grid2{grid-template-columns:1fr 1fr!important;gap:8px!important}.card{padding:15px!important}.item .body{min-width:0!important}.item .amt{font-size:13px!important}.big-number{font-size:34px!important}.mid-number{font-size:20px!important}}@media(max-width:360px){.navbtn{font-size:8px!important}.navbtn svg{width:19px!important;height:19px!important}}`;document.head.appendChild(st);
function cloudStatus(ok){window.cloudOnline=!!ok;const d=document.getElementById('syncDot'),x=document.getElementById('syncText');if(d)d.className='sync-dot '+(ok?'online':'offline');if(x)x.textContent=ok?'в облаке':'только локально'}
async function cloudGet(){const r=await fetch(SB_URL+'/rest/v1/transactions?select=id,date,type,category,amount,shift,comment&category=eq.'+encodeURIComponent(META)+'&order=id.desc&limit=1',{headers:H,cache:'no-store'});if(!r.ok)throw Error('Supabase '+r.status);const a=await r.json();return a[0]||null}
async function cloudPut(force){if(!window.STATE||syncing)return;const json=JSON.stringify(STATE);if(!force&&json===lastCloud)return;syncing=true;try{const payload={date:today(),type:'Meta',category:META,amount:0,shift:'',comment:JSON.stringify({version:6,state:JSON.parse(json),updatedAt:Date.now()})};let r;if(cloudId)r=await fetch(SB_URL+'/rest/v1/transactions?id=eq.'+encodeURIComponent(cloudId),{method:'PATCH',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(payload)});else r=await fetch(SB_URL+'/rest/v1/transactions',{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw Error('Supabase '+r.status);const rows=await r.json();if(rows[0])cloudId=rows[0].id;lastCloud=json;cloudStatus(true)}catch(e){console.warn('Cloud sync:',e);cloudStatus(false)}finally{syncing=false}}
function isUserDataEmpty(s){if(!s||typeof s!=='object')return true;const arr=['income','expenses','reserves','recurring','debts','reserveOps'];if(arr.some(k=>Array.isArray(s[k])&&s[k].length))return false;const settings=s.settings||{};if(n(settings.currentBalance)!==0)return false;if(typeof s.startBalance!=='undefined'&&n(s.startBalance)!==0)return false;return true}
async function cloudLoad(){try{const row=await cloudGet();cloudStatus(true);if(row)cloudId=row.id;const remote=row?.comment?JSON.parse(row.comment).state:null;if(remote&&typeof remote==='object'&&isUserDataEmpty(STATE)){Object.keys(STATE).forEach(k=>delete STATE[k]);Object.keys(remote).forEach(k=>STATE[k]=remote[k]);if(typeof saveState==='function')saveState()}cloudReady=true;lastCloud=JSON.stringify(STATE);if(typeof render==='function')render()}catch(e){cloudStatus(false);cloudReady=true;console.warn('Cloud unavailable:',e)}}
/* Hook common local persistence functions so every change is sent immediately. */
function hookPersistence(){['saveState','persist'].forEach(name=>{const fn=window[name];if(typeof fn!=='function'||fn.__cloudV6)return;window[name]=function(){const r=fn.apply(this,arguments);setTimeout(()=>cloudPut(true),0);return r};window[name].__cloudV6=true});}
setInterval(()=>{if(cloudReady&&window.STATE){hookPersistence();const j=JSON.stringify(STATE);if(j!==lastCloud)cloudPut(false)}},1000);window.addEventListener('online',()=>cloudPut(true));function boot(){if(window.STATE){hookPersistence();cloudLoad()}else setTimeout(boot,100)}boot();
})();
