const CACHE_NAME='kopeyka-cloud-v25';
function patch(html){
 html=html.replace(/function shiftIncomeAmount\(shift\)\s*\{[\s\S]*?\n\}/m,'function shiftIncomeAmount(shift){ return 0; }');
 html=html.replace(/<script src="\.\/fixes\.js\?v=[^"]+"><\/script>/g,'');
 html=html.replace(/<script src="\.\/cloud-loader\.js\?v=[^"]+"><\/script>/g,'');
 html=html.replace(/<script src="\.\/auth-cloud\.js\?v=[^"]+"><\/script>/g,'');
 html=html.replace(/<script src="\.\/finance-core\.js\?v=[^"]+"><\/script>/g,'');
 html=html.replace(/<script src="\.\/ui-finance-v4\.js\?v=[^"]+"><\/script>/g,'');
 html=html.replace(/<script src="\.\/ui-balance-fix\.js\?v=[^"]+"><\/script>/g,'');
 html=html.replace('</body>','<script src="./auth-cloud.js?v=4"></script><script src="./finance-core.js?v=5"></script><script src="./ui-finance-v4.js?v=3"></script><script src="./ui-balance-fix.js?v=3"></script></body>');
 const css='<style id="kopeyka-ui-v25">@media(max-width:899px){#main{padding-bottom:calc(118px + var(--safe-bottom))!important}.bottomnav{position:fixed!important;left:0!important;right:0!important;bottom:0!important;z-index:1000!important;width:100%!important;min-height:72px!important;padding-bottom:calc(8px + var(--safe-bottom))!important}.navbtn{min-height:56px!important;padding:7px 6px!important;flex:1 1 0!important;width:0!important;min-width:0!important;display:flex!important;align-items:center!important;justify-content:center!important}.fab{right:18px!important;bottom:calc(94px + var(--safe-bottom))!important;z-index:1100!important;width:56px!important;height:56px!important}.overlay{z-index:5000!important;padding-bottom:0!important}.modal{max-height:calc(100dvh - 24px)!important;min-height:0!important;padding:20px 18px calc(30px + var(--safe-bottom))!important;overflow-y:auto!important;-webkit-overflow-scrolling:touch!important}.modal-actions{position:sticky!important;bottom:0!important;margin:18px -2px 0!important;padding-top:10px!important;background:linear-gradient(transparent,var(--surface) 22%)!important;z-index:2!important}.modal-actions .btn{min-height:48px!important}}@media(min-width:900px){.fab{z-index:1100!important}}</style>';
 if(!html.includes('kopeyka-ui-v25'))html=html.replace('</head>',css+'</head>'); return html;
}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.add('./')).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin===self.location.origin&&(u.pathname.endsWith('/')||u.pathname.endsWith('/index.html'))){e.respondWith((async()=>{try{const r=await fetch(e.request,{cache:'no-store'});return new Response(patch(await r.text()),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'}})}catch(_){const c=await caches.match('./');return c?new Response(patch(await c.text()),{headers:{'Content-Type':'text/html;charset=utf-8'}}):Response.error()}})());return}e.respondWith(fetch(e.request,{cache:'no-store'}).catch(()=>caches.match(e.request).then(r=>r||Response.error())))});